#*******************************************************************************
#.travis.yml
#*******************************************************************************

#Purpose:
#Travis CI is a hosted continuous integration service, that is, it allows 
#running code directly from a repository and checking that the code acts as 
#expected. The purpose of the .travis.yml file is to give instructions to Travis 
#CI on how to do the work.
#Authors:
#Alan D. Snow, 2016


#*******************************************************************************
#System specifications for Travis CI
#*******************************************************************************
language: python
python:
  - "2.7"
  - "3.5"
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - python: "3.5"

#*******************************************************************************
#Before installing RAPIDpy
#*******************************************************************************
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y gcc gfortran g++ build-essential

#-------------------------------------------------------------------------------
#Add miniconda - from https://gist.github.com/dan-blanchard/7045057
#-----------------------------------------------------------------------------
- wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $HOME/miniconda
- export PATH=$HOME/miniconda/bin:$PATH
- conda update --yes conda python
#create environment in conda
- conda create --yes --name gssha python=$TRAVIS_PYTHON_VERSION
- source activate gssha

#-------------------------------------------------------------------------------
# Install required python packages
#-----------------------------------------------------------------------------
- conda install --yes python=$TRAVIS_PYTHON_VERSION nose numpy netCDF4 gdal pyproj
- pip install coveralls

#-------------------------------------------------------------------------------
# Install GRIB API
#-------------------------------------------------------------------------------
- cd $TRAVIS_BUILD_DIR 
- mkdir ../installz
- cd ../installz
#install cmake 3.6.2 on Ubuntu 14.04
- mkdir cmake_install
- cd cmake_install
- wget https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.sh
- sudo chmod u+x cmake-3.6.2-Linux-x86_64.sh
- ./cmake-3.6.2-Linux-x86_64.sh --skip-license
- export PATH=$PWD/bin:$PATH
- cd ..
#install grib
- wget -O grib_api-1.17.0-Source.tar.gz https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.17.0-Source.tar.gz?api=v2
- tar xf grib_api-1.17.0-Source.tar.gz
- mkdir grib_api-build
- mkdir grib_api-install
- cd grib_api-build
- cmake ../grib_api-1.17.0-Source -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../installz/grib_api-install
- make
- make install


#-------------------------------------------------------------------------------
# Install pygrib
#-------------------------------------------------------------------------------
- cd .. 
- git clone https://github.com/jswhit/pygrib.git
- cd pygrib
- echo "[directories]" > setup.cfg
- echo "grib_api_dir = $TRAVIS_BUILD_DIR/../installz/grib_api-install" >> setup.cfg
- python setup.py build
- python setup.py install

#*******************************************************************************
#Installing GSSHApy
#*******************************************************************************
install:
- cd $TRAVIS_BUILD_DIR
- python setup.py install

#*******************************************************************************
#Testing GSSHApy
#*******************************************************************************
- cd $TRAVIS_BUILD_DIR/tests
script: 
- nosetests --with-coverage --cover-package=gsshapy,gridtogssha
##ADD Coveralls stats for code coverage
after_success:
  - coveralls

