# gsshapy-conda-env.yml
# Configuration file for creating a Conda Environment with dependencies needed for GSSHApy.
# Create the environment by running the following command (after installing Miniconda):
# os: linux
#   $ conda env create -f gsshapy-conda-env.yml

name: gssha
channels:
- conda-forge
- defaults
dependencies:
- python=2
- mock
- nose
- numpy
- pandas
- scipy
- netCDF4
- gdal
- shapely
- psycopg2
- pygrib
- pyproj
- python-dateutil
- rtree
- sphinx
- pip:
  - future
  - mapkit
  - requests
  - six
  - sphinxcontrib-napoleon
  - sqlalchemy
  - timezonefinder